# Generated by Django 4.2.5 on 2023-09-19 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50, verbose_name='Имя задачи')),
                ('task_description', models.CharField(max_length=50, verbose_name='Описание задачи')),
                ('date_create', models.DateTimeField(verbose_name='Дата создания задачи')),
                ('execution_status', models.CharField(max_length=50, verbose_name='Статус выполнения')),
                ('date_execution', models.DateTimeField(verbose_name='Дата выполнения задачи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
