# Generated by Django 4.2.5 on 2023-09-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_task_description_tasks_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='execution_status',
            field=models.CharField(default='Ожидает выполнения', max_length=50, verbose_name='Статус выполнения'),
        ),
    ]
