# Generated by Django 4.2.5 on 2023-09-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_description_alter_tasks_execution_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date_execution',
            field=models.DateTimeField(default='', verbose_name='Дата выполнения задачи'),
        ),
    ]
