# Generated by Django 4.2.5 on 2023-09-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_options_alter_tasks_date_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_execution',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения задачи'),
        ),
    ]
