# Generated by Django 4.2.5 on 2023-09-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_tasks_date_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='execution_status',
            field=models.CharField(blank=True, default='Ожидает выполнения', max_length=50, null=True, verbose_name='Статус выполнения'),
        ),
    ]
